apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-kafka
  namespace: default
spec:
  chart:
    spec:
      chart: kafka
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: ">=3.4.0"
  interval: 1m0s
